<?php

/**
 * @file
 * Primary module hooks for semanticbits_lastmodifiedblock module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function modifiedpageoftheday_theme($existing, $type, $theme, $path){
    
    return [
        'block_modifiedpageoftheday'=>[
            'variables'=>[
                'posts'=>[],
            ],
        ],
    ];
    
}
